import { properties } from '@estatepilot/shared'
import { ArrowRight, BarChart3, Bot, CalendarCheck, CheckCircle2, Map, ShieldCheck, Sparkles, Users } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import { PropertyCard } from '@/components/property-card'
import { PublicShell } from '@/components/public-shell'
import { SearchBox } from '@/components/search-box'
import { Button } from '@/components/ui'

export default function HomePage() {
  return <PublicShell>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="hero-kicker"><span className="pulse"/>Pakistan’s AI-powered property platform</div><h1 className="display">Find a place that <em style={{fontFamily:'Georgia,serif',fontWeight:400,color:'var(--primary)'}}>fits your life.</em></h1><p className="subheading">Search naturally in English or Urdu. Compare intelligently. Book confidently. EstatePilot turns a complicated property journey into a clear next step.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link href="/properties"><Button size="lg">Explore properties <ArrowRight size={17}/></Button></Link><Link href="/dashboard"><Button size="lg" variant="outline">For real-estate agencies</Button></Link></div></div><div className="hero-visual"><Image className="hero-image" src={properties[0].image} alt="Modern luxury villa in Pakistan" fill priority sizes="(max-width: 820px) 100vw, 48vw"/><div className="floating-card top"><div style={{display:'flex',alignItems:'center',gap:11}}><div className="match-ring"><span>96%</span></div><div><strong style={{fontSize:13}}>Great match</strong><div className="muted" style={{fontSize:11,marginTop:3}}>Budget · location</div></div></div></div><div className="floating-card bottom"><div style={{display:'flex',alignItems:'center',gap:10}}><span className="feature-icon" style={{margin:0,width:38,height:38}}><Sparkles size={18}/></span><div><strong style={{fontSize:13}}>AI explains every match</strong><div className="muted" style={{fontSize:11,marginTop:3}}>No endless, irrelevant listings</div></div></div></div></div></div></section>
    <SearchBox/>
    <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Handpicked for you</div><h2 className="heading" style={{marginTop:10}}>Homes worth discovering</h2></div><Link href="/properties"><Button variant="outline">View all properties <ArrowRight size={16}/></Button></Link></div><div className="property-grid">{properties.slice(0,3).map((p)=><PropertyCard key={p.id} property={p}/>)}</div></div></section>
    <section className="section feature-band" id="about"><div className="container feature-grid"><div><div className="eyebrow" style={{color:'var(--lime)'}}>Built around your decisions</div><h2 className="heading" style={{marginTop:12}}>An intelligent co-pilot, not another listing portal.</h2><p className="subheading">EstatePilot understands intent, remembers preferences and helps you move from “just looking” to a confirmed viewing—without losing context.</p><div style={{marginTop:30}}><Link href="/properties"><Button variant="secondary" size="lg">Start an AI search <ArrowRight size={17}/></Button></Link></div></div><div className="feature-list">{[[Bot,'Natural conversation','Search in everyday English or Roman Urdu.'],[Map,'Location intelligence','Understand nearby places, commute and area fit.'],[BarChart3,'Clear comparison','See trade-offs and an explainable AI match score.'],[CalendarCheck,'Instant viewing','Pick a time, confirm and keep every detail together.']].map(([Icon,title,text])=><div className="feature-item" key={String(title)}><span className="feature-icon"><Icon size={20}/></span><strong>{String(title)}</strong><p className="muted" style={{fontSize:13,lineHeight:1.6,marginBottom:0}}>{String(text)}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="stats-strip"><div className="stat"><strong>2,400+</strong><span className="muted">Verified listings</span></div><div className="stat"><strong>18 min</strong><span className="muted">Average agent response</span></div><div className="stat"><strong>92%</strong><span className="muted">Search satisfaction</span></div><div className="stat"><strong>3 cities</strong><span className="muted">And expanding</span></div></div></div></section>
    <section className="section" id="agents" style={{paddingTop:20}}><div className="container"><div className="section-head"><div><div className="eyebrow">For modern agencies</div><h2 className="heading" style={{marginTop:10}}>Every lead. Every conversation. One calm workspace.</h2><p className="subheading">Qualify leads, manage properties, book viewings and know exactly where your pipeline stands.</p></div></div><div className="feature-list" style={{gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))'}}>{[[Users,'Unified CRM'],[Sparkles,'AI lead qualification'],[CalendarCheck,'Viewing management'],[ShieldCheck,'Multi-tenant security']].map(([Icon,title])=><div className="card" key={String(title)} style={{padding:22}}><span className="feature-icon"><Icon size={20}/></span><strong>{String(title)}</strong><p className="muted" style={{fontSize:13,lineHeight:1.6}}>Designed for real workflows, responsive across phone, tablet and desktop.</p><div style={{display:'flex',alignItems:'center',gap:7,color:'var(--primary)',fontSize:12,fontWeight:700}}><CheckCircle2 size={14}/>Included in the agency workspace</div></div>)}</div></div></section>
  </PublicShell>
}
