'use client'

import { BarChart3, Bell, Bot, Building2, CalendarDays, CreditCard, FileText, Home, KanbanSquare, LogOut, Menu, MessageSquare, Plug, Search, Settings, Users, Workflow, X } from 'lucide-react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useRouter } from 'next/navigation'
import { FormEvent, useState } from 'react'
import { Button, Input } from './ui'
import { canAccess, type SessionUser } from '@/lib/permissions'

const nav=[
  ['Workspace',[['Overview','/dashboard',Home],['Leads','/dashboard/leads',Users],['Pipeline','/dashboard/pipeline',KanbanSquare],['Conversations','/dashboard/conversations',MessageSquare],['Properties','/dashboard/properties',Building2],['Appointments','/dashboard/appointments',CalendarDays]]],
  ['Automation',[['Follow-up workflows','/dashboard/workflows',Workflow],['Knowledge base','/dashboard/knowledge',FileText],['AI configuration','/dashboard/ai-settings',Bot]]],
  ['Management',[['Analytics','/dashboard/analytics',BarChart3],['Team members','/dashboard/team',Users],['Integrations','/dashboard/integrations',Plug],['Billing','/dashboard/billing',CreditCard],['Settings','/dashboard/settings',Settings]]]
] as const

function SidebarNav({role,onNavigate}:{role:SessionUser['role'];onNavigate?:()=>void}){const path=usePathname();return <><Link href="/" className="brand"><span className="brand-mark" style={{background:'var(--lime)',color:'#173c2f'}}><Building2 size={19}/></span>EstatePilot AI</Link><nav className="sidebar-nav" aria-label="Dashboard navigation">{nav.map(([group,items])=>{const permitted=items.filter(([,href])=>canAccess(role,href==='/dashboard'?'overview':href.split('/').pop()??''));return permitted.length?<div key={group}><div className="sidebar-label">{group}</div>{permitted.map(([label,href,Icon])=><Link key={href} href={href} onClick={onNavigate} className={`sidebar-link ${path===href?'active':''}`}><Icon size={17}/><span>{label}</span></Link>)}</div>:null})}</nav></>}

export function DashboardShell({children,session}:{children:React.ReactNode;session:SessionUser}){const [mobile,setMobile]=useState(false);const [query,setQuery]=useState('');const [notifications,setNotifications]=useState(false);const router=useRouter();const roleLabel=session.role==='manager'?'Agency manager':session.role==='agent'?'Property advisor':'Customer support';const initials=session.name.split(' ').map((part)=>part[0]).join('').slice(0,2);async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.replace('/auth');router.refresh()}function search(e:FormEvent){e.preventDefault();if(query.trim())router.push(`/properties?q=${encodeURIComponent(query.trim())}`)}return <div className="dashboard-shell"><aside className="sidebar"><SidebarNav role={session.role}/></aside><div className="dashboard-main"><header className="dashboard-topbar"><div style={{display:'flex',alignItems:'center',gap:10,minWidth:0}}><Button variant="ghost" size="icon" className="mobile-menu-button" onClick={()=>setMobile(true)} aria-label="Open dashboard menu"><Menu size={20}/></Button><form onSubmit={search} style={{position:'relative',width:'min(360px,35vw)'}}><Search size={15} style={{position:'absolute',left:13,top:14,color:'var(--muted)'}}/><Input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search leads, properties…" style={{paddingLeft:36,minHeight:40}}/></form></div><div style={{display:'flex',alignItems:'center',gap:8,position:'relative'}}><Button variant="ghost" size="icon" aria-label="Notifications" onClick={()=>setNotifications(!notifications)}><Bell size={18}/></Button>{notifications&&<div className="notification-popover"><strong>Priority updates</strong><p>3 viewings are scheduled today.</p><p>2 hot leads need a response.</p><Button size="sm" variant="outline" onClick={()=>router.push('/dashboard/appointments')}>Open schedule</Button></div>}<div className="person"><span className="avatar">{initials}</span><div className="desktop-only"><strong style={{fontSize:12}}>{session.name}</strong><div className="muted" style={{fontSize:10}}>{roleLabel}</div></div></div><Button variant="ghost" size="icon" onClick={logout} aria-label="Sign out" title="Sign out"><LogOut size={18}/></Button></div></header>{children}</div>{mobile&&<div style={{position:'fixed',inset:0,zIndex:80,background:'rgba(8,25,18,.45)'}} onClick={()=>setMobile(false)}><aside className="sidebar" style={{display:'block',width:280,position:'absolute',left:0,top:0}} onClick={(e)=>e.stopPropagation()}><Button variant="ghost" size="icon" style={{position:'absolute',right:10,top:10,color:'white'}} onClick={()=>setMobile(false)}><X/></Button><SidebarNav role={session.role} onNavigate={()=>setMobile(false)}/><Button variant="ghost" onClick={logout} style={{color:'white',width:'100%',marginTop:20}}><LogOut size={17}/>Sign out</Button></aside></div>}</div>}
