'use client'

import { appointments, leads as seedLeads, properties } from '@estatepilot/shared'
import type { Lead, LeadStage } from '@estatepilot/shared'
import { BarChart3, BellRing, Bot, CalendarCheck, CheckCircle2, CircleDollarSign, FileText, GripVertical, Mail, MapPin, MessageSquare, MoreHorizontal, Plus, Search, Send, Settings, ShieldCheck, Sparkles, Upload, Users, Workflow, Zap } from 'lucide-react'
import Image from 'next/image'
import { useState } from 'react'
import { Badge, Button, Card, Input, Select, Textarea } from './ui'

const titles:Record<string,[string,string]>={leads:['Leads','Qualify, assign and move every opportunity forward.'],pipeline:['Sales pipeline','A live view of every lead from first contact to close.'],conversations:['Conversations','AI and human conversations together in one inbox.'],properties:['Properties','Manage verified listings, availability and assigned agents.'],appointments:['Appointments','Coordinate physical and virtual property viewings.'],workflows:['Follow-up workflows','Personalized sequences that keep leads moving.'],knowledge:['Knowledge base','Ground AI answers in approved agency documents.'],analytics:['Analytics','Understand demand, conversion and team performance.'],team:['Team members','Manage roles, territories and lead capacity.'],'ai-settings':['AI configuration','Control tone, handoff rules and data boundaries.'],integrations:['Integrations','Connect the tools your agency already uses.'],billing:['Billing','Plan, usage and subscription controls.'],settings:['Settings','Agency profile, security and preferences.']}

export function DashboardSection({section}:{section:string}){const [title,subtitle]=titles[section]??['Workspace','EstatePilot agency operations'];return <div className="dashboard-content"><div className="dashboard-title"><div><div className="eyebrow">Agency workspace</div><h1 style={{fontSize:30,letterSpacing:'-.04em',margin:'7px 0'}}>{title}</h1><p className="muted" style={{margin:0,fontSize:13}}>{subtitle}</p></div><SectionAction section={section}/></div><SectionBody section={section}/></div>}

function SectionAction({section}:{section:string}){if(['leads','properties','team'].includes(section))return <Button><Plus size={16}/>Add {section==='properties'?'property':section==='team'?'member':'lead'}</Button>;if(section==='knowledge')return <Button><Upload size={16}/>Upload document</Button>;if(section==='workflows')return <Button><Workflow size={16}/>New workflow</Button>;return <Button variant="outline"><Settings size={16}/>Configure</Button>}

function SectionBody({section}:{section:string}){switch(section){case'leads':return <LeadsTable/>;case'pipeline':return <Pipeline/>;case'conversations':return <Conversations/>;case'properties':return <Properties/>;case'appointments':return <Appointments/>;case'workflows':return <Workflows/>;case'knowledge':return <Knowledge/>;case'analytics':return <Analytics/>;case'team':return <Team/>;case'ai-settings':return <AISettings/>;case'integrations':return <Integrations/>;case'billing':return <Billing/>;default:return <AgencySettings/>}}

function FilterBar(){return <Card style={{padding:12,display:'flex',gap:10,flexWrap:'wrap',marginBottom:16}}><div style={{position:'relative',flex:'1 1 220px'}}><Search size={15} style={{position:'absolute',left:12,top:14,color:'var(--muted)'}}/><Input placeholder="Search…" style={{paddingLeft:35}}/></div><Select style={{width:'auto',minWidth:150}}><option>All statuses</option><option>Active</option><option>Pending</option></Select><Button variant="outline">Filters</Button></Card>}

function LeadsTable(){return <><FilterBar/><Card className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Lead</th><th>Looking for</th><th>Budget</th><th>AI score</th><th>Stage</th><th>Assigned</th><th/></tr></thead><tbody>{seedLeads.map((l)=><tr key={l.id}><td><div className="person"><span className="avatar">{l.name.split(' ').map(x=>x[0]).join('')}</span><div><strong>{l.name}</strong><div className="muted" style={{fontSize:10}}>{l.phone}</div></div></div></td><td>{l.purpose==='buy'?'Buy':'Rent'} · {l.area}</td><td>{l.budget}</td><td><Badge tone={l.temperature==='hot'?'danger':l.temperature==='warm'?'warning':'neutral'}>{l.score} {l.temperature}</Badge></td><td style={{textTransform:'capitalize'}}>{l.stage}</td><td>{l.assignedAgent}</td><td><Button variant="ghost" size="icon"><MoreHorizontal size={16}/></Button></td></tr>)}</tbody></table></div></Card></>}

const stages:LeadStage[]=['new','qualified','viewing','negotiation','won']
function Pipeline(){const [items,setItems]=useState<Lead[]>(seedLeads);function move(id:string,stage:LeadStage){setItems((all)=>all.map((l)=>l.id===id?{...l,stage}:l));fetch(`${process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api'}/leads/${id}/stage`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage})}).catch(()=>undefined)}return <div className="kanban">{stages.map((stage)=><section className="kanban-col" key={stage} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>move(e.dataTransfer.getData('lead'),stage)}><div className="kanban-head"><span style={{textTransform:'capitalize'}}>{stage}</span><Badge>{items.filter((l)=>l.stage===stage).length}</Badge></div>{items.filter((l)=>l.stage===stage).map((l)=><Card className="lead-card" key={l.id} draggable onDragStart={(e)=>e.dataTransfer.setData('lead',l.id)}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><div className="person"><GripVertical size={14} color="var(--muted)"/><strong>{l.name}</strong></div><span className="lead-score">{l.score}</span></div><p className="muted" style={{lineHeight:1.5}}>{l.purpose} · {l.area}<br/>{l.budget}</p><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center'}}><Badge tone={l.temperature==='hot'?'danger':l.temperature==='warm'?'warning':'neutral'}>{l.temperature}</Badge><span className="muted" style={{fontSize:10}}>{l.lastActivity}</span></div></Card>)}</section>)}</div>}

function Conversations(){const [sent,setSent]=useState(['Hi Maham, I found three furnished apartments close to Blue Area within your budget.','The Skyline apartment looks good. Is it available this weekend?']);const [value,setValue]=useState('');return <Card className="inbox"><div className="thread-list">{seedLeads.slice(0,5).map((l,i)=><div className={`thread-item ${i===0?'active':''}`} key={l.id}><span className="avatar">{l.name.split(' ').map(x=>x[0]).join('')}</span><div style={{minWidth:0}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{fontSize:13}}>{l.name}</strong><span className="muted" style={{fontSize:9}}>{l.lastActivity}</span></div><p className="muted" style={{fontSize:11,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',margin:'5px 0'}}>Interested in {l.area} properties…</p><Badge tone={i<2?'danger':'neutral'}>{i<2?'AI active':'Human'}</Badge></div></div>)}</div><div className="conversation"><div className="panel-head" style={{padding:'14px 18px',margin:0,borderBottom:'1px solid var(--border)'}}><div className="person"><span className="avatar">MA</span><div><strong>Maham Ali</strong><div className="muted" style={{fontSize:10}}>Hot lead · 76 score</div></div></div><Button variant="outline" size="sm">Take over</Button></div><div className="conversation-messages">{sent.map((text,i)=><div className={`message ${i%2?'user':'ai'}`} key={i}>{text}</div>)}<div className="message ai">Yes, it is available Saturday at 11:30 AM or 3:00 PM. Would you like me to book it?</div></div><form className="chat-form" onSubmit={(e)=>{e.preventDefault();if(value.trim()){setSent((m)=>[...m,value]);setValue('')}}}><Input value={value} onChange={(e)=>setValue(e.target.value)} placeholder="Reply as Areeba…"/><Button size="icon"><Send size={17}/></Button></form></div></Card>}

function Properties(){return <><FilterBar/><div className="table-wrap" style={{background:'white'}}><table className="data-table"><thead><tr><th>Property</th><th>Purpose</th><th>Price</th><th>Status</th><th>AI views</th><th>Agent</th><th/></tr></thead><tbody>{properties.map((p)=><tr key={p.id}><td><div className="person"><Image src={p.image} alt="" width={52} height={42} style={{width:52,height:42,objectFit:'cover',borderRadius:8}}/><div><strong>{p.title}</strong><div className="muted" style={{fontSize:10}}>{p.area}, {p.city}</div></div></div></td><td style={{textTransform:'capitalize'}}>{p.purpose}</td><td>{p.priceLabel}</td><td><Badge tone="success">{p.status}</Badge></td><td>{Math.floor(320*p.matchScore/100)}</td><td>{p.agent.name}</td><td><Button variant="ghost" size="icon"><MoreHorizontal size={16}/></Button></td></tr>)}</tbody></table></div></>}

function Appointments(){return <div className="dashboard-grid" style={{gridTemplateColumns:'1fr .62fr',marginTop:0}}><Card className="panel"><div className="panel-head"><strong>Upcoming viewings</strong><Badge tone="brand">{appointments.length} scheduled</Badge></div>{appointments.map((a)=><div key={a.id} style={{display:'grid',gridTemplateColumns:'70px 1fr auto',gap:14,padding:'17px 0',borderTop:'1px solid var(--border)',alignItems:'center'}}><div style={{textAlign:'center'}}><strong style={{fontSize:20}}>{a.date.slice(-2)}</strong><div className="muted" style={{fontSize:10}}>JUL</div></div><div><strong>{a.leadName} · {a.time}</strong><div className="muted" style={{fontSize:11,marginTop:4}}>{a.propertyTitle} with {a.agentName}</div></div><Badge tone={a.status==='confirmed'?'success':'warning'}>{a.status}</Badge></div>)}</Card><Card className="panel"><div className="panel-head"><strong>Agent availability</strong><CalendarCheck size={18} color="var(--primary)"/></div>{['Areeba Khan','Hamza Siddiqui','Sara Ahmed'].map((a,i)=><div className="person" key={a} style={{padding:'12px 0',borderTop:'1px solid var(--border)'}}><span className="avatar">{a.split(' ').map(x=>x[0]).join('')}</span><div style={{flex:1}}><strong>{a}</strong><div className="muted" style={{fontSize:10}}>{i===1?'2 slots left':'Available today'}</div></div><Badge tone="success">Online</Badge></div>)}</Card></div>}

function Workflows(){const rows=[['New inquiry nurture','Website & AI leads','5 steps','Active','184'],['Viewing reminder','Booked viewings','3 steps','Active','42'],['Cold lead re-engagement','No reply for 7 days','4 steps','Paused','0'],['Post-viewing follow-up','Viewing completed','3 steps','Active','31']];return <div className="feature-list" style={{gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))'}}>{rows.map(([name,trigger,steps,status,enrolled])=><Card className="panel" key={name}><div className="panel-head"><span className="feature-icon" style={{margin:0}}><Workflow size={19}/></span><Badge tone={status==='Active'?'success':'neutral'}>{status}</Badge></div><h3>{name}</h3><p className="muted" style={{fontSize:12}}>Starts when: {trigger}</p><div style={{display:'flex',justifyContent:'space-between',borderTop:'1px solid var(--border)',paddingTop:14,fontSize:12}}><span>{steps}</span><strong>{enrolled} enrolled</strong></div></Card>)}</div>}

function Knowledge(){const docs=[['DHA Lahore Area Guide.pdf','Area guide','42 chunks','Ready'],['Agency Policies 2026.pdf','Policy','18 chunks','Ready'],['Payment Plans.xlsx','Pricing','33 chunks','Ready'],['Bahria Town FAQs.docx','FAQ','Processing','Indexing']];return <><Card style={{border:'1px dashed #9bb8a8',padding:30,textAlign:'center',marginBottom:18,background:'#f5f8f4'}}><Upload size={34} color="var(--primary)"/><h3>Drop approved agency documents here</h3><p className="muted" style={{fontSize:13}}>PDF, DOCX, XLSX or TXT · tenant-isolated and source-tracked</p><Button variant="outline">Choose files</Button></Card><Card className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Document</th><th>Type</th><th>Vector index</th><th>Status</th><th/></tr></thead><tbody>{docs.map((d)=><tr key={d[0]}><td><div className="person"><span className="metric-icon"><FileText size={18}/></span><strong>{d[0]}</strong></div></td><td>{d[1]}</td><td>{d[2]}</td><td><Badge tone={d[3]==='Ready'?'success':'warning'}>{d[3]}</Badge></td><td><Button variant="ghost" size="icon"><MoreHorizontal size={16}/></Button></td></tr>)}</tbody></table></div></Card></>}

function Analytics(){const locations=[['DHA Lahore',88],['Blue Area',74],['Gulberg',63],['Clifton',57],['Bahria Karachi',49]];return <><div className="metric-grid">{[['PKR 84.5M','Estimated pipeline'],['18.6%','Lead conversion'],['38','Viewings this month'],['68%','AI qualification rate']].map(([v,l])=><Card className="metric-card" key={l}><BarChart3 size={18} color="var(--primary)"/><strong className="metric-value">{v}</strong><span className="muted" style={{fontSize:12}}>{l}</span></Card>)}</div><div className="dashboard-grid"><Card className="panel"><div className="panel-head"><strong>Conversion funnel</strong><Badge tone="success">+12.4%</Badge></div>{[['New inquiries',412,100],['Qualified',282,68],['Viewings',126,31],['Negotiation',54,13],['Won',23,6]].map(([label,count,w])=><div key={String(label)} style={{marginBottom:15}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,marginBottom:6}}><span>{label}</span><strong>{count}</strong></div><div style={{height:9,background:'#e8ece8',borderRadius:99}}><div style={{height:'100%',width:`${w}%`,background:'var(--primary)',borderRadius:99}}/></div></div>)}</Card><Card className="panel"><div className="panel-head"><strong>Most requested locations</strong><MapPin size={17} color="var(--primary)"/></div>{locations.map(([label,value])=><div key={label} style={{marginBottom:15}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,marginBottom:6}}><span>{label}</span><strong>{value}%</strong></div><div style={{height:7,background:'#e8ece8',borderRadius:99}}><div style={{height:'100%',width:`${value}%`,background:'var(--lime)',borderRadius:99}}/></div></div>)}</Card></div></>}

function Team(){const members=[['Areeba Khan','Agency manager','DHA & Gulberg','12','Online'],['Hamza Siddiqui','Senior agent','Islamabad','9','Online'],['Sara Ahmed','Property advisor','Karachi','7','In viewing'],['Ali Hassan','Junior agent','Lahore','5','Offline']];return <><FilterBar/><div className="feature-list" style={{gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))'}}>{members.map((m)=><Card className="panel" key={m[0]}><div className="person"><span className="avatar" style={{width:48,height:48}}>{m[0].split(' ').map(x=>x[0]).join('')}</span><div><strong>{m[0]}</strong><div className="muted" style={{fontSize:11}}>{m[1]}</div></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:18}}><div className="detail-stat"><strong>{m[2]}</strong><div className="muted" style={{fontSize:9}}>Territory</div></div><div className="detail-stat"><strong>{m[3]}</strong><div className="muted" style={{fontSize:9}}>Open leads</div></div></div><Badge tone={m[4]==='Online'?'success':m[4]==='Offline'?'neutral':'warning'} style={{marginTop:14}}>{m[4]}</Badge></Card>)}</div></>}

function Toggle({defaultOn=true}:{defaultOn?:boolean}){const [on,setOn]=useState(defaultOn);return <button onClick={()=>setOn(!on)} aria-pressed={on} style={{width:42,height:24,border:0,borderRadius:99,background:on?'var(--primary)':'#cbd2cd',padding:3,cursor:'pointer'}}><span style={{display:'block',width:18,height:18,borderRadius:'50%',background:'white',transform:on?'translateX(18px)':'none',transition:'.2s'}}/></button>}
function SettingRow({icon:Icon,title,text,on=true}:{icon:typeof Bot;title:string;text:string;on?:boolean}){return <div style={{display:'flex',gap:13,alignItems:'center',padding:'17px 0',borderTop:'1px solid var(--border)'}}><span className="metric-icon"><Icon size={18}/></span><div style={{flex:1}}><strong>{title}</strong><div className="muted" style={{fontSize:11,marginTop:3}}>{text}</div></div><Toggle defaultOn={on}/></div>}
function AISettings(){return <div className="settings-grid"><div className="settings-tabs">{['Assistant behavior','Lead qualification','Human handoff','Safety rules','Languages'].map((x,i)=><button className={`settings-tab ${i===0?'active':''}`} key={x}>{x}</button>)}</div><Card className="panel"><h3>Assistant behavior</h3><div className="form-field"><label htmlFor="tone">Default tone</label><Select id="tone"><option>Professional and warm</option><option>Concise</option><option>Consultative</option></Select></div><div className="form-field" style={{marginTop:15}}><label htmlFor="prompt">Agency guidance</label><Textarea id="prompt" defaultValue="Help customers discover verified properties. Never invent availability, pricing or legal information. Ask concise clarifying questions and explain recommendation reasons."/></div><div style={{marginTop:20}}><SettingRow icon={Sparkles} title="English and Urdu" text="Detect the customer’s language automatically."/><SettingRow icon={ShieldCheck} title="Verified data only" text="Answer listing questions from approved records."/><SettingRow icon={Users} title="High-value handoff" text="Notify an agent when lead score reaches 75."/></div><Button style={{marginTop:16}}>Save AI configuration</Button></Card></div>}

function Integrations(){const tools=[{Icon:Mail,name:'Resend',text:'Transactional email and reminders',connected:true},{Icon:MessageSquare,name:'Twilio WhatsApp',text:'Customer follow-ups',connected:false},{Icon:CalendarCheck,name:'Google Calendar',text:'Agent availability and viewings',connected:false},{Icon:MapPin,name:'Mapbox',text:'Maps, geocoding and distance',connected:true},{Icon:Zap,name:'OpenRouter',text:'Free-model AI routing',connected:true},{Icon:BellRing,name:'Sentry',text:'Errors and performance',connected:false}];return <div className="feature-list" style={{gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))'}}>{tools.map(({Icon,name,text,connected})=><Card className="panel" key={name}><div className="panel-head"><span className="metric-icon"><Icon size={19}/></span><Badge tone={connected?'success':'neutral'}>{connected?'Connected':'Not connected'}</Badge></div><h3>{name}</h3><p className="muted" style={{fontSize:12,lineHeight:1.6}}>{text}</p><Button variant={connected?'outline':'primary'} style={{width:'100%'}}>{connected?'Manage':'Connect'}</Button></Card>)}</div>}

function Billing(){return <div className="dashboard-grid" style={{gridTemplateColumns:'1.2fr .8fr',marginTop:0}}><Card className="panel"><Badge tone="brand">Portfolio plan</Badge><h2 style={{fontSize:30,letterSpacing:'-.04em'}}>Free demo workspace</h2><p className="muted">Designed for portfolio evaluation with seeded data and free-tier integrations.</p><div style={{display:'grid',gap:12,margin:'25px 0'}}>{['Up to 5 team members','2,500 active properties','AI assistant with OpenRouter free models','CRM, appointments and analytics'].map((x)=><span key={x} style={{display:'flex',gap:9,fontSize:13}}><CheckCircle2 size={17} color="var(--primary)"/>{x}</span>)}</div><Button variant="outline">Manage plan</Button></Card><Card className="panel"><CircleDollarSign size={25} color="var(--primary)"/><h3>Current usage</h3>{[['AI requests','128 / 1,500'],['Team seats','4 / 5'],['Storage','1.2 / 5 GB']].map(([a,b])=><div key={a} style={{display:'flex',justifyContent:'space-between',padding:'13px 0',borderTop:'1px solid var(--border)',fontSize:12}}><span className="muted">{a}</span><strong>{b}</strong></div>)}</Card></div>}

function AgencySettings(){return <div className="settings-grid"><div className="settings-tabs">{['Agency profile','Branding','Security','Notifications','Data & privacy'].map((x,i)=><button className={`settings-tab ${i===0?'active':''}`} key={x}>{x}</button>)}</div><Card className="panel"><h3>Agency profile</h3><div className="form-grid"><div className="form-field"><label htmlFor="agency">Agency name</label><Input id="agency" defaultValue="EstatePilot Demo Realty"/></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:15}}><div className="form-field"><label htmlFor="phone">Business phone</label><Input id="phone" defaultValue="+92 300 555 0100"/></div><div className="form-field"><label htmlFor="city">Head office</label><Select id="city"><option>Lahore</option><option>Islamabad</option><option>Karachi</option></Select></div></div><div className="form-field"><label htmlFor="address">Address</label><Textarea id="address" defaultValue="48-C, Commercial Broadway, DHA Phase 6, Lahore"/></div><SettingRow icon={ShieldCheck} title="Require two-factor authentication" text="Enforce stronger sign-in security for managers."/><SettingRow icon={BellRing} title="Priority lead notifications" text="Notify assigned agents about hot leads immediately."/><Button>Save changes</Button></div></Card></div>}
