'use client'

import type { Property } from '@estatepilot/shared'
import { ListFilter, MapPinned, Search, SlidersHorizontal } from 'lucide-react'
import { useMemo, useState } from 'react'
import { PropertyCard } from './property-card'
import { Button, Card, Input, Select } from './ui'

export function PropertyExplorer({initialProperties,initialQuery='',initialPurpose=''}:{initialProperties:Property[];initialQuery?:string;initialPurpose?:string}){
  const [query,setQuery]=useState(initialQuery);const [purpose,setPurpose]=useState(initialPurpose);const [city,setCity]=useState('');const [beds,setBeds]=useState('');const [type,setType]=useState('');const [showMap,setShowMap]=useState(true)
  const filtered=useMemo(()=>initialProperties.filter((p)=>{const hay=`${p.title} ${p.city} ${p.area} ${p.description} ${p.amenities.join(' ')}`.toLowerCase();const words=query.toLowerCase().split(/\s+/).filter((w)=>w.length>2);return(!query||words.some((w)=>hay.includes(w)))&&(!purpose||p.purpose===purpose)&&(!city||p.city===city)&&(!beds||p.bedrooms>=Number(beds))&&(!type||p.type===type)}),[initialProperties,query,purpose,city,beds,type])
  return <><div className="filters"><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',left:14,top:15,color:'var(--muted)'}}/><Input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search area, city or feature" style={{paddingLeft:40}}/></div><Select value={purpose} onChange={(e)=>setPurpose(e.target.value)} aria-label="Purpose"><option value="">Buy & rent</option><option value="buy">Buy</option><option value="rent">Rent</option></Select><Select value={city} onChange={(e)=>setCity(e.target.value)} aria-label="City"><option value="">All cities</option><option>Islamabad</option><option>Lahore</option><option>Karachi</option></Select><Select value={type} onChange={(e)=>setType(e.target.value)} aria-label="Property type"><option value="">All types</option><option value="house">House</option><option value="apartment">Apartment</option><option value="plot">Plot</option><option value="commercial">Commercial</option></Select><Select value={beds} onChange={(e)=>setBeds(e.target.value)} aria-label="Bedrooms"><option value="">Any beds</option><option value="2">2+ beds</option><option value="3">3+ beds</option><option value="4">4+ beds</option></Select></div><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',margin:'18px 0',flexWrap:'wrap'}}><div><strong>{filtered.length} properties</strong><span className="muted" style={{fontSize:13}}> · Sorted by best AI match</span></div><Button variant="outline" size="sm" onClick={()=>setShowMap(!showMap)}>{showMap?<ListFilter size={15}/>:<MapPinned size={15}/>} {showMap?'Hide map':'Show map'}</Button></div><div className={showMap?'results-layout':undefined}><div className="property-grid" style={{gridTemplateColumns:showMap?'repeat(2,minmax(0,1fr))':undefined}}>{filtered.map((p)=><PropertyCard key={p.id} property={p}/>)}</div>{showMap&&<Card className="map-panel" aria-label="Property map"><div className="map-grid"/><div className="map-road"/>{filtered.slice(0,5).map((p,i)=><div className="map-pin" key={p.id} style={{left:`${15+(i*17)%68}%`,top:`${18+(i*23)%65}%`}}>{p.priceLabel.replace('PKR ','')}</div>)}<div style={{position:'absolute',bottom:14,left:14,right:14,padding:12,background:'rgba(255,255,255,.94)',borderRadius:12,fontSize:12,display:'flex',gap:8,alignItems:'center'}}><SlidersHorizontal size={15} color="var(--primary)"/>Mapbox activates when NEXT_PUBLIC_MAPBOX_TOKEN is added.</div></Card>}</div>{filtered.length===0&&<Card className="empty-state"><MapPinned size={36} color="var(--primary)"/><h3>No exact match yet</h3><p className="muted">Try a wider area or remove one filter. The AI assistant can also suggest close alternatives.</p></Card>}</>
}
