import { Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common'
import { appointments, leads, properties, type Appointment, type Lead, type LeadStage, type Property, type PropertyStatus } from '@estatepilot/shared'
import pg from 'pg'
import { randomUUID } from 'node:crypto'

type NewProperty=Omit<Property,'id'|'slug'|'matchScore'|'images'|'agent'> & {agentId?:string}
export type WorkspaceRole='manager'|'agent'|'support'
export type WorkspaceUser={id:string;email:string;name:string;role:WorkspaceRole}

@Injectable()
export class DatabaseService implements OnModuleInit, OnModuleDestroy {
  private pool:pg.Pool|null=null
  private memory={properties:[...properties],leads:[...leads],appointments:[...appointments]}
  async onModuleInit(){
    if(!process.env.DATABASE_URL)return
    this.pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5})
    this.pool.on('connect',(client)=>{void client.query('set search_path to estatepilot, public')})
    try{await this.pool.query('select 1');await this.ensureAuthSchema();await this.ensureDemoSeed()}catch(error){console.warn('Postgres unavailable; using seeded memory repository',error);await this.pool.end();this.pool=null}
  }
  async onModuleDestroy(){await this.pool?.end()}
  isConnected(){return Boolean(this.pool)}
  private async ensureAuthSchema(){
    if(!this.pool)return
    await this.pool.query(`alter table users add column if not exists password_hash text; alter table users add column if not exists password_updated_at timestamptz; alter table organization_members drop constraint if exists organization_members_role_check; alter table organization_members add constraint organization_members_role_check check(role in ('platform_admin','manager','agent','support','viewer')); create index if not exists organization_members_access_idx on organization_members(organization_id,user_id,status)`)
    await this.pool.query(`insert into organizations(id,name,slug) values('org-demo','EstatePilot Demo Realty','estatepilot-demo') on conflict(id) do nothing`)
    const staff:[string,string,WorkspaceRole,string][]=[['manager@demo.estatepilot.pk','Areeba Khan','manager','EstatePilot2026!'],['agent@demo.estatepilot.pk','Hamza Siddiqui','agent','AgentPilot2026!'],['support@demo.estatepilot.pk','Sara Ahmed','support','SupportPilot2026!']]
    for(const [email,name,role,password] of staff){
      const {rows:[user]}=await this.pool.query<{id:string}>(`insert into users(email,full_name,password_hash,password_updated_at) values($1,$2,crypt($3,gen_salt('bf',12)),now()) on conflict(email) do update set full_name=excluded.full_name,password_hash=coalesce(users.password_hash,excluded.password_hash),password_updated_at=coalesce(users.password_updated_at,excluded.password_updated_at) returning id`,[email,name,password])
      await this.pool.query(`insert into organization_members(organization_id,user_id,role,status) values('org-demo',$1,$2,'active') on conflict(organization_id,user_id) do update set role=excluded.role,status='active'`,[user.id,role])
    }
  }
  async authenticateUser(email:string,password:string):Promise<WorkspaceUser|null>{
    if(!this.pool)return null
    const {rows}=await this.pool.query<WorkspaceUser>(`select u.id,u.email,u.full_name as name,om.role from users u join organization_members om on om.user_id=u.id where lower(u.email)=lower($1) and om.organization_id='org-demo' and om.status='active' and u.password_hash is not null and u.password_hash=crypt($2,u.password_hash) limit 1`,[email.trim(),password])
    const user=rows[0]
    return user&&['manager','agent','support'].includes(user.role)?user:null
  }
  private async ensureDemoSeed(){
    if(!this.pool)return
    const {rows:[{count}]}=await this.pool.query<{count:string}>('select count(*) from properties')
    if(Number(count)>=properties.length)return
    const client=await this.pool.connect()
    const agentIds:Record<string,string>={'Areeba Khan':'agent-areeba','Hamza Siddiqui':'agent-hamza','Sara Ahmed':'agent-sara'}
    try{
      await client.query('begin')
      for(const property of properties){
        await client.query(`insert into properties(id,organization_id,slug,title,description,purpose,property_type,city,area,address,latitude,longitude,price,price_label,bedrooms,bathrooms,size,size_unit,furnished,amenities,status,verified,featured,match_score,agent_id) values($1,'org-demo',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24) on conflict(id) do update set title=excluded.title,description=excluded.description,price=excluded.price,price_label=excluded.price_label,status=excluded.status,featured=excluded.featured,match_score=excluded.match_score,updated_at=now()`,[property.id,property.slug,property.title,property.description,property.purpose,property.type,property.city,property.area,property.address,property.latitude,property.longitude,property.price,property.priceLabel,property.bedrooms,property.bathrooms,property.size,property.sizeUnit,property.furnished,property.amenities,property.status,property.verified,property.featured,property.matchScore,agentIds[property.agent.name]??'agent-areeba'])
        await client.query(`insert into property_images(organization_id,property_id,url,alt_text) select 'org-demo',$1,$2,$3 where not exists(select 1 from property_images where property_id=$1 and url=$2)`,[property.id,property.image,property.title])
      }
      for(const lead of leads)await client.query(`insert into leads(id,organization_id,name,email,phone,purpose,budget,preferred_area,score,temperature,stage,source) values($1,'org-demo',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) on conflict(id) do nothing`,[lead.id,lead.name,lead.email,lead.phone,lead.purpose,lead.budget,lead.area,lead.score,lead.temperature,lead.stage,lead.source])
      for(const appointment of appointments){const property=properties.find((item)=>item.title===appointment.propertyTitle)??properties[0];await client.query(`insert into appointments(id,organization_id,property_id,lead_name,agent_name,viewing_date,viewing_time,viewing_type,status) values($1,'org-demo',$2,$3,$4,$5,$6,$7,$8) on conflict(id) do nothing`,[appointment.id,property.id,appointment.leadName,appointment.agentName,appointment.date,appointment.time,appointment.type,appointment.status])}
      await client.query('commit')
    }catch(error){await client.query('rollback');throw error}finally{client.release()}
  }
  private mapProperty(row:Record<string,unknown>):Property{return{id:String(row.id),slug:String(row.slug),title:String(row.title),purpose:row.purpose as Property['purpose'],type:row.property_type as Property['type'],city:String(row.city),area:String(row.area),address:String(row.address),price:Number(row.price),currency:'PKR',priceLabel:String(row.price_label),bedrooms:Number(row.bedrooms),bathrooms:Number(row.bathrooms),size:Number(row.size),sizeUnit:row.size_unit as Property['sizeUnit'],furnished:Boolean(row.furnished),verified:Boolean(row.verified),featured:Boolean(row.featured),status:row.status as PropertyStatus,matchScore:Number(row.match_score),description:String(row.description),amenities:(row.amenities as string[])??[],image:String(row.image??properties[0].image),images:(row.images as string[])?.length?(row.images as string[]):[String(row.image??properties[0].image)],latitude:Number(row.latitude),longitude:Number(row.longitude),agent:{name:String(row.agent_name??'EstatePilot Advisor'),title:String(row.agent_title??'Property Advisor'),phone:String(row.agent_phone??'+92 300 000 0000'),avatar:String(row.agent_avatar??'EP')}}}
  async getProperties(){if(!this.pool)return this.memory.properties;const {rows}=await this.pool.query(`select p.*,a.name agent_name,a.title agent_title,a.phone agent_phone,upper(left(a.name,1)||substring(a.name from position(' ' in a.name)+1 for 1)) agent_avatar,(select array_agg(pi.url order by pi.position) from property_images pi where pi.property_id=p.id) images,(select pi.url from property_images pi where pi.property_id=p.id order by pi.position limit 1) image from properties p left join agents a on a.id=p.agent_id order by p.featured desc,p.match_score desc`);return rows.map((r)=>this.mapProperty(r))}
  async getProperty(id:string){if(!this.pool)return this.memory.properties.find((p)=>p.id===id||p.slug===id)??null;const {rows}=await this.pool.query(`select p.*,a.name agent_name,a.title agent_title,a.phone agent_phone,(select array_agg(pi.url order by pi.position) from property_images pi where pi.property_id=p.id) images,(select pi.url from property_images pi where pi.property_id=p.id order by pi.position limit 1) image from properties p left join agents a on a.id=p.agent_id where p.id=$1 or p.slug=$1 limit 1`,[id]);return rows[0]?this.mapProperty(rows[0]):null}
  async createProperty(input:NewProperty){const id=`prop-${randomUUID().slice(0,8)}`;const slug=`${input.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${randomUUID().slice(0,5)}`;const property:Property={...input,id,slug,matchScore:80,images:[input.image],agent:{name:'Areeba Khan',title:'Senior Property Advisor',phone:'+92 300 555 0192',avatar:'AK'}};this.memory.properties.unshift(property);if(this.pool){await this.pool.query(`insert into properties(id,organization_id,slug,title,description,purpose,property_type,city,area,address,latitude,longitude,price,price_label,bedrooms,bathrooms,size,size_unit,furnished,amenities,status,verified,featured,match_score,agent_id) values($1,'org-demo',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,80,$24)`,[id,slug,input.title,input.description,input.purpose,input.type,input.city,input.area,input.address,input.latitude,input.longitude,input.price,input.priceLabel,input.bedrooms,input.bathrooms,input.size,input.sizeUnit,input.furnished,input.amenities,input.status,input.verified,input.featured,input.agentId??'agent-areeba']);await this.pool.query(`insert into property_images(organization_id,property_id,url,alt_text) values('org-demo',$1,$2,$3)`,[id,input.image,input.title])}return property}
  async updatePropertyStatus(id:string,status:PropertyStatus){const property=this.memory.properties.find((p)=>p.id===id);if(property)property.status=status;if(this.pool)await this.pool.query('update properties set status=$1,updated_at=now() where id=$2',[status,id]);return property??await this.getProperty(id)}
  private mapLead(row:Record<string,unknown>):Lead{return{id:String(row.id),name:String(row.name),email:String(row.email??''),phone:String(row.phone),purpose:row.purpose as Lead['purpose'],budget:String(row.budget),area:String(row.preferred_area),score:Number(row.score),temperature:row.temperature as Lead['temperature'],stage:row.stage as LeadStage,assignedAgent:String(row.assigned_agent??'Unassigned'),lastActivity:'Recently',source:String(row.source)}}
  async getLeads(){if(!this.pool)return this.memory.leads;const {rows}=await this.pool.query('select l.*,a.name assigned_agent from leads l left join agents a on a.id=l.assigned_agent_id order by l.created_at desc');return rows.map((r)=>this.mapLead(r))}
  async createLead(input:{name:string;email?:string;phone:string;purpose:'buy'|'rent';budget:string;area:string;source:string}){const lead:Lead={...input,email:input.email??'',id:`lead-${randomUUID().slice(0,8)}`,score:45,temperature:'warm',stage:'new',assignedAgent:'Unassigned',lastActivity:'Just now'};this.memory.leads.unshift(lead);if(this.pool)await this.pool.query(`insert into leads(id,organization_id,name,email,phone,purpose,budget,preferred_area,score,temperature,stage,source) values($1,'org-demo',$2,$3,$4,$5,$6,$7,45,'warm','new',$8)`,[lead.id,lead.name,lead.email,lead.phone,lead.purpose,lead.budget,lead.area,lead.source]);return lead}
  async updateLeadStage(id:string,stage:LeadStage){const lead=this.memory.leads.find((l)=>l.id===id);if(lead){lead.stage=stage;lead.lastActivity='Just now'}if(this.pool)await this.pool.query('update leads set stage=$1,updated_at=now() where id=$2',[stage,id]);return lead??(await this.getLeads()).find((l)=>l.id===id)??null}
  private mapAppointment(row:Record<string,unknown>):Appointment{return{id:String(row.id),leadName:String(row.lead_name),propertyTitle:String(row.property_title),agentName:String(row.agent_name),date:String(row.viewing_date).slice(0,10),time:String(row.viewing_time),type:row.viewing_type as Appointment['type'],status:row.status as Appointment['status']}}
  async getAppointments(){if(!this.pool)return this.memory.appointments;const {rows}=await this.pool.query('select a.*,p.title property_title from appointments a join properties p on p.id=a.property_id order by viewing_date,viewing_time');return rows.map((r)=>this.mapAppointment(r))}
  async createAppointment(input:{propertyId:string;leadName:string;date:string;time:string;type:'physical'|'virtual'}){const property=await this.getProperty(input.propertyId)??this.memory.properties[0];const appointment:Appointment={id:`apt-${randomUUID().slice(0,8)}`,leadName:input.leadName,propertyTitle:property.title,agentName:property.agent.name,date:input.date,time:input.time,type:input.type,status:'pending'};this.memory.appointments.push(appointment);if(this.pool)await this.pool.query(`insert into appointments(id,organization_id,property_id,lead_name,agent_name,viewing_date,viewing_time,viewing_type,status) values($1,'org-demo',$2,$3,$4,$5,$6,$7,'pending')`,[appointment.id,property.id,appointment.leadName,appointment.agentName,appointment.date,appointment.time,appointment.type]);return appointment}
  async updateAppointment(id:string,input:{status?:Appointment['status'];date?:string;time?:string}){const appointment=this.memory.appointments.find((a)=>a.id===id);if(appointment)Object.assign(appointment,input);if(this.pool)await this.pool.query('update appointments set status=coalesce($1,status),viewing_date=coalesce($2,viewing_date),viewing_time=coalesce($3,viewing_time) where id=$4',[input.status??null,input.date??null,input.time??null,id]);return appointment??(await this.getAppointments()).find((a)=>a.id===id)??null}
}
