import { Inject, Injectable } from '@nestjs/common'
import type { Property } from '@estatepilot/shared'
import { DatabaseService } from './database.service.js'
import { OpenRouterService } from './openrouter.service.js'

export function deterministicIntent(query:string){const q=query.toLowerCase();const city=['islamabad','lahore','karachi'].find((x)=>q.includes(x));const purpose=q.includes('rent')||q.includes('monthly')||q.includes('kiraye')||q.includes('rent pe')?'rent':q.includes('buy')||q.includes('sale')||q.includes('kharid')||q.includes('crore')?'buy':undefined;const bedrooms=Number(q.match(/(\d+)\s*(?:bed|bedroom|bed\s*room)/)?.[1]??0)||undefined;const furnished=q.includes('furnished')||q.includes('furnish');return{city,purpose,bedrooms,furnished:furnished||undefined}}
@Injectable()
export class EstateService {constructor(@Inject(DatabaseService) private db:DatabaseService,@Inject(OpenRouterService) private ai:OpenRouterService){}
  async search(query:string){const parsed=(await this.ai.extractSearch(query))??deterministicIntent(query);const all=await this.db.getProperties();const area=['bahria town','dha','gulberg','blue area','clifton','f-8','f-10'].find((item)=>query.toLowerCase().includes(item));const matching=all.filter((p)=>!parsed.city||p.city.toLowerCase()===parsed.city.toLowerCase()).filter((p)=>!parsed.purpose||p.purpose===parsed.purpose).filter((p)=>!parsed.bedrooms||p.bedrooms>=parsed.bedrooms).filter((p)=>!parsed.furnished||p.furnished);const areaMatches=area?matching.filter((p)=>p.area.toLowerCase().includes(area)):matching;const filtered=areaMatches.length?areaMatches:matching;return{intent:parsed,properties:(filtered.length?filtered:all).sort((a,b)=>b.matchScore-a.matchScore),explanation:filtered.length?'Matches ranked by location, requirements and verified availability.':'No exact match; showing the closest verified alternatives.'}}
  async chat(message:string,language:'en'|'ur'){const result=await this.search(message);const matched=result.properties.slice(0,3);const romanUrdu=language==='ur'||/\b(mujhe|mjy|chahi|chahye|hai|hain|kharid|mein|lahore|karachi)\b/i.test(message);const context=matched.map((p:Property)=>`${p.title}; ${p.area}, ${p.city}; ${p.priceLabel}; ${p.bedrooms} beds; ${p.status}`).join('\n');const aiReply=await this.ai.chat(message,romanUrdu?'ur':language,context);const intent=result.intent;const criteria=[intent.city&&intent.city[0].toUpperCase()+intent.city.slice(1),intent.purpose==='buy'?'buy':'rent',intent.bedrooms?`${intent.bedrooms}+ beds`:undefined].filter(Boolean).join(' · ');const options=matched.map((p)=>`${p.title} (${p.area}, ${p.priceLabel})`).join('; ');const fallback=romanUrdu?`Ji, ${criteria||'aap ki requirement'} ke liye ${matched.length} verified options milay: ${options}. ${intent.bedrooms?'Yeh options aap ki bedroom requirement ko meet karte hain. ':''}Budget share kar dein to main shortlist aur precise bana doon.`:`I found ${matched.length} verified matches for ${criteria||'your requirement'}: ${options}. ${intent.bedrooms?'Each option meets your bedroom requirement. ':''}Share your budget and I can narrow this further.`;const usableAiReply=aiReply&&matched.some((property)=>aiReply.includes(property.title))?aiReply:null;return{reply:usableAiReply??fallback,properties:matched}}
}
