import { z } from 'zod'

export const searchSchema=z.object({query:z.string().min(2).max(500),purpose:z.enum(['buy','rent']).optional(),city:z.string().max(80).optional()})
export const chatSchema=z.object({message:z.string().min(1).max(2000),language:z.enum(['en','ur']).default('en'),conversationId:z.string().optional()})
export const leadSchema=z.object({name:z.string().min(2),email:z.email().optional(),phone:z.string().min(10),purpose:z.enum(['buy','rent']),budget:z.string(),area:z.string(),source:z.string().default('Website')})
export const stageSchema=z.object({stage:z.enum(['new','qualified','viewing','negotiation','won','lost'])})
export const appointmentSchema=z.object({propertyId:z.string(),leadName:z.string().min(2),email:z.email().optional(),phone:z.string().optional(),date:z.string(),time:z.string(),type:z.enum(['physical','virtual']).default('physical'),notes:z.string().max(1000).optional()})
export const appointmentUpdateSchema=z.object({status:z.enum(['confirmed','pending','cancelled']).optional(),date:z.string().optional(),time:z.string().optional()}).refine((value)=>Object.keys(value).length>0)
export const propertySchema=z.object({title:z.string().min(3),description:z.string().min(10),purpose:z.enum(['buy','rent']),type:z.enum(['house','apartment','plot','commercial']),city:z.string().min(2),area:z.string().min(2),address:z.string().min(4),price:z.number().positive(),currency:z.literal('PKR').default('PKR'),priceLabel:z.string().min(3),bedrooms:z.number().int().nonnegative(),bathrooms:z.number().int().nonnegative(),size:z.number().positive(),sizeUnit:z.enum(['Marla','Kanal','Sq. Ft.','Sq. Yd.']),furnished:z.boolean().default(false),verified:z.boolean().default(true),featured:z.boolean().default(false),status:z.enum(['available','reserved','sold','rented']).default('available'),amenities:z.array(z.string()).default([]),image:z.url(),latitude:z.number(),longitude:z.number(),agentId:z.string().optional()})
export const propertyStatusSchema=z.object({status:z.enum(['available','reserved','sold','rented'])})
